name: Docker

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build simage
        run: docker build -t omertalmi5/github-action .



      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u omertalmi --password-stdin

      - name: Push images
        run: |
          docker push omertalmi5/github-action